RESILIENCE_SEARCHES = [
    "Extreme Heat",
    "Extreme Cold",
    "Heat Waves",
    "Drought",
    "Flooding",
    "Tropical Cyclone",
    "Hurricane",
    "Wildfires",
    "Convective Storm",
    "Sea Level Rise",
    "Permafrost Thaw",
    "Ocean Acidification",
    "Carbon Dioxide Fertilizer",
    "Rising Ocean Temperature",
    "Snowmelt Timing",
    "Arctic Sea Ice",
    "Ice Storm",
    "Derecho",
    "Tornado",
    "Extreme Wind",
    "Urban Heat Island",
    "Coastal Flooding",  # terms from here onward from jlnav
    "Extreme Rainfall",
    "Blizzard",
]
